-- Clear broken record cover URLs
UPDATE media SET cover_url = NULL WHERE media_type = 'record' AND title IN (
  'House of Sugar',
  'Rocket',
  'Parrot Flies',
  'Teen Dream',
  'Crazy For You',
  'John Wesley Harding',
  'Before the Flood',
  'For Emma, Forever Ago',
  'Tender Buttons',
  'Analphabetapolothology',
  'Teaser and the Firecat',
  'Zoo',
  'Mingus Ah Um',
  'Young States',
  'Heaven or Las Vegas',
  'Around the Fur',
  'Milo Gets Bootlegged',
  'Milo Goes to College',
  'Everything Sucks',
  'Stratosphere',
  'Songs to Learn & Sing',
  'Rationale',
  'Visions',
  'Christmas',
  'Instigator',
  'Wildlife',
  'Part and Parcel',
  'End Measured Mile',
  'Real Talk',
  'Man Overboard',
  'Amperland, NY',
  'Atom Heart Mother',
  'Evil Empire',
  'Live at the Harlem Square Club',
  'Goo',
  'Little Creatures',
  'Folklore',
  'Talon of the Hawk',
  'A Light for Attracting Attention',
  'The Queen is Dead',
  'The Smiths',
  'Meat is Murder',
  'Under Soil & Dirt',
  'Whenever, If Ever',
  'Parting The Sea Between Brightness And Me',
  'Purgatory',
  'Wavvves',
  'King of the Beach',
  'Being There',
  'American Heartbreak'
);